---
title: "Brainstorm/notes"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(httr)
library(XML)
library(lubridate)
library(rlang)
library(rlist)
```


Setting the user data to grab
```{r}
user <- "Sci_Karate"
```

Grabbing initial list of games
```{r}
user_request <- paste("https://www.boardgamegeek.com/xmlapi2/collection?username=", user, "&subtype=boardgame&own=1", sep = "")

user_data <- GET(user_request) %>%
  xmlParse() %>%
  xmlToList()

game_id <- lapply(user_data[1:(length(user_data) - 1)], function(x) as.character(x[[".attrs"]][["objectid"]])) %>%
  unlist()
```


Pulling data on games using the IDs
```{r}
user_games_request <- "https://www.boardgamegeek.com/xmlapi2/thing?id="
for (id in seq_along(game_id)) {
  user_games_request <- paste(user_games_request, game_id[[id]], ",", sep = "")
}
user_games_request <- str_sub(user_games_request, end = -2)
user_games_request <- paste(user_games_request, "&stats=1&comments=1&ratingcomments=1", sep = "")

user_games <- GET(user_games_request) %>%
  xmlParse() %>%
  xmlToList()

games_df <- list()
for (i in seq_along(user_games)) {
  vars <- unique(names(user_games[[i]]))
  vars <- vars[! vars %in% c("link", ".attrs", "poll", "comments")]
  games_df[[i]] <- list()
  for (j in seq_along(vars)) {
    if (vars[[j]] == "name") {
      games_df[[i]][["name"]] <- user_games[[i]][["name"]][["value"]]
    } else if (vars[[j]] == "statistics") {
      use <- c("usersrated", "average", "bayesaverage", "stddev", "owned", "trading", "wanting", "wishing", "numcomments", "numweights", "averageweight")
      for (stat in use) {
        games_df[[i]][[stat]] <- user_games[[i]][["statistics"]][["ratings"]][[stat]]
      }
    } else {
      games_df[[i]][[vars[[j]]]] <- user_games[[i]][[vars[[j]]]]
    }
  }
  rownames <- names(games_df[[i]])
  games <- unlist(games_df[[i]])
  games_df[[i]] <- data.frame(matrix(games, nrow = length(games), byrow = T), row.names = rownames)
  name <- as.character(games_df[[i]]["name", ])
  games_df[[name]] <- duplicate(games_df[[i]])
  games_df[[i]] <- NULL
}

games_comments <- tibble(game = c(NA), 
                         rating = c(NA), 
                         comment = c(NA))
curr_row <- 0
for (i in seq_along(user_games)) {
  if (class(user_games[[i]]) != "character") {
    for (j in seq_along(user_games[[i]][["comments"]])) {
      curr_row <- max(curr_row+1, i+(j-1))
      if (length(user_games[[i]][["comments"]][[j]]) > 2) {
        games_comments[curr_row, "game"] <- user_games[[i]][["name"]][["value"]]
        if (user_games[[i]][["comments"]][[j]][["rating"]] != "N/A") {
          games_comments[curr_row, "rating"] <- user_games[[i]][["comments"]][[j]][["rating"]]
        }
        games_comments[curr_row, "comment"] <- user_games[[i]][["comments"]][[j]][["value"]]
      }
    }
  }
}

game_names <- sapply(games_df, function(x) as.character(x["name", 1]))
all_games <- list.cbind(games_df)
colnames(all_games) <- game_names

all_games_tidy <- all_games[1:(ncol(all_games) - 1)] %>%
  t() %>%
  as.data.frame() %>%
  select(3, 1:2, 4:ncol(.)) %>%
  mutate_at(vars(1:11), as.character) %>%
  mutate_at(vars(5:11), as.numeric)

rownames(all_games_tidy) <- NULL
```